import boto3

"""
Django settings for chat_app project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ygr=eee_8n8(xvk5-haamm(mp25i&fw5zqxg(v)1jxs3aq58yg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chat_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chat_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# DynamoDB configuration
# AWS and DynamoDB configuration
AWS_REGION = 'eu-north-1'
AWS_ACCESS_KEY_ID = 'your_aws_access_key_id'
AWS_SECRET_ACCESS_KEY = 'your_aws_secret_access_key'
# AWS_DYNAMODB_ENDPOINT_URL = 'https://dynamodb.us-east-1.amazonaws.com'
AWS_DYNAMODB_ENDPOINT_URL = 'http://localhost:8000'


# DYNAMODB_TABLES = {
#     'users': {
#         'table_name': 'users',
#         'key_schema': [
#             {'AttributeName': 'id', 'KeyType': 'HASH'},
#             {'AttributeName': 'username',},
#             {'AttributeName': 'email',},
#             {'AttributeName': 'password',},
#         ],
#         'attribute_definitions': [
#             {'AttributeName': 'id', 'AttributeType': 'S'}
#         ],
#         'provisioned_throughput': {
#             'ReadCapacityUnits': 5,
#             'WriteCapacityUnits': 5
#         }
#     },
#     'chats': {
#         'table_name': 'chats',
#         'key_schema': [
#             {'AttributeName': 'id', 'KeyType': 'HASH'},
#             {'AttributeName': 'senderId'},
#             {'AttributeName': 'recipientId'},
#             {'AttributeName': 'content'},
#             {'AttributeName': 'seen'},
#             {'AttributeName': 'updatedAt'},
#         ],
#         'attribute_definitions': [
#             {'AttributeName': 'id', 'AttributeType': 'S'}
#         ],
#         'provisioned_throughput': {
#             'ReadCapacityUnits': 5,
#             'WriteCapacityUnits': 5
#         }
#     }
# }



# Create a DynamoDB client
dynamodb = boto3.resource('dynamodb', region_name=AWS_REGION, endpoint_url=AWS_DYNAMODB_ENDPOINT_URL)